/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */
val ktor_version: String by project
val ktorm_version: String by project
val postgresql_driver_version: String by project

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
    kotlin("plugin.serialization")

    id("com.google.protobuf")
    
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation(Kotlin.test.junit5)

    // Use the JUnit 5 integration.
    testImplementation(Testing.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher:_")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:_")

    implementation("io.ktor:ktor-client-jvm:_")
    implementation(Ktor.plugins.serialization.kotlinx.json)
    implementation("io.ktor:ktor-server-core-jvm:_")
    implementation("io.ktor:ktor-server-netty-jvm:_")
    implementation("io.ktor:ktor-server-status-pages-jvm:_")
    implementation("io.ktor:ktor-server-default-headers-jvm:_")
    implementation(Ktor.server.contentNegotiation)
    implementation("io.ktor:ktor-server-tests-jvm:_")

    implementation("org.ktorm:ktorm-core:_")
    implementation("org.ktorm:ktorm-support-postgresql:_")
    
    implementation("org.postgresql:postgresql:_")
    
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:_")

    implementation(KotlinX.datetime)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("miithermostat.ApplicationKt")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
